package com.tunisales.inventory.service;

import com.tunisales.inventory.client.PlatformNotificationClient;
import com.tunisales.inventory.domain.StockAudit;
import com.tunisales.inventory.domain.StockAuditLine;
import com.tunisales.inventory.domain.StockItem;
import com.tunisales.inventory.domain.enumeration.AuditMode;
import com.tunisales.inventory.domain.enumeration.AuditResolution;
import com.tunisales.inventory.domain.enumeration.AuditStatus;
import com.tunisales.inventory.repository.StockAuditLineRepository;
import com.tunisales.inventory.repository.StockAuditRepository;
import com.tunisales.inventory.repository.StockItemRepository;
import com.tunisales.inventory.service.dto.NotificationPayloadDTO;
import com.tunisales.inventory.service.dto.StockAuditDTO;
import com.tunisales.inventory.service.mapper.StockAuditMapper;
import java.time.ZonedDateTime;
import java.util.NoSuchElementException;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Service Implementation for managing {@link StockAudit}.
 *
 * <p>In addition to the standard CRUD generated by JHipster, this service
 * implements the extended audit workflow defined in Étape 1.3:
 * <ul>
 *   <li>{@link #recordCount(Long, int)}: enter a head-count and auto-switch to
 *       {@link AuditMode#SCAN_ONE_BY_ONE} on discrepancy.</li>
 *   <li>{@link #scanLine(Long, String)}: register an IMEI scan during a scan
 *       audit, flagging items that fall outside the audit perimeter.</li>
 *   <li>{@link #closeWithParallel(Long)}: close an audit and reconcile it with
 *       its parallel pair (commercial vs magasinier). Discrepancies reopen
 *       both audits and emit an {@code AUDIT_DISCREPANCY} notification.</li>
 * </ul>
 * </p>
 */
@Service
@Transactional
public class StockAuditService {

    private final Logger log = LoggerFactory.getLogger(StockAuditService.class);

    private final StockAuditRepository stockAuditRepository;

    private final StockAuditMapper stockAuditMapper;

    private final StockAuditLineRepository stockAuditLineRepository;

    private final StockItemRepository stockItemRepository;

    private final PlatformNotificationClient notificationClient;

    public StockAuditService(
        StockAuditRepository stockAuditRepository,
        StockAuditMapper stockAuditMapper,
        StockAuditLineRepository stockAuditLineRepository,
        StockItemRepository stockItemRepository,
        PlatformNotificationClient notificationClient
    ) {
        this.stockAuditRepository = stockAuditRepository;
        this.stockAuditMapper = stockAuditMapper;
        this.stockAuditLineRepository = stockAuditLineRepository;
        this.stockItemRepository = stockItemRepository;
        this.notificationClient = notificationClient;
    }

    public StockAuditDTO save(StockAuditDTO stockAuditDTO) {
        log.debug("Request to save StockAudit : {}", stockAuditDTO);
        StockAudit stockAudit = stockAuditMapper.toEntity(stockAuditDTO);
        if (stockAudit.getAuditMode() == null) {
            stockAudit.setAuditMode(AuditMode.COUNT);
        }
        stockAudit = stockAuditRepository.save(stockAudit);
        return stockAuditMapper.toDto(stockAudit);
    }

    public StockAuditDTO update(StockAuditDTO stockAuditDTO) {
        log.debug("Request to update StockAudit : {}", stockAuditDTO);
        StockAudit stockAudit = stockAuditMapper.toEntity(stockAuditDTO);
        stockAudit = stockAuditRepository.save(stockAudit);
        return stockAuditMapper.toDto(stockAudit);
    }

    public Optional<StockAuditDTO> partialUpdate(StockAuditDTO stockAuditDTO) {
        log.debug("Request to partially update StockAudit : {}", stockAuditDTO);

        return stockAuditRepository
            .findById(stockAuditDTO.getId())
            .map(existingStockAudit -> {
                stockAuditMapper.partialUpdate(existingStockAudit, stockAuditDTO);

                return existingStockAudit;
            })
            .map(stockAuditRepository::save)
            .map(stockAuditMapper::toDto);
    }

    @Transactional(readOnly = true)
    public Page<StockAuditDTO> findAll(Pageable pageable) {
        log.debug("Request to get all StockAudits");
        return stockAuditRepository.findAll(pageable).map(stockAuditMapper::toDto);
    }

    public Page<StockAuditDTO> findAllWithEagerRelationships(Pageable pageable) {
        return stockAuditRepository.findAllWithEagerRelationships(pageable).map(stockAuditMapper::toDto);
    }

    @Transactional(readOnly = true)
    public Optional<StockAuditDTO> findOne(Long id) {
        log.debug("Request to get StockAudit : {}", id);
        return stockAuditRepository.findOneWithEagerRelationships(id).map(stockAuditMapper::toDto);
    }

    public void delete(Long id) {
        log.debug("Request to delete StockAudit : {}", id);
        stockAuditRepository.deleteById(id);
    }

    // ===================================================================
    // 1.3 — Extended audit workflow
    // ===================================================================

    /**
     * Record a head-count for an audit. If {@code counted} differs from the
     * audit's {@code theoreticalCount}, the audit is automatically switched to
     * {@link AuditMode#SCAN_ONE_BY_ONE} so the auditor must reconcile each item
     * by IMEI.
     */
    public StockAuditDTO recordCount(Long auditId, int counted) {
        log.debug("Request to record count {} on audit {}", counted, auditId);
        StockAudit audit = stockAuditRepository
            .findById(auditId)
            .orElseThrow(() -> new NoSuchElementException("StockAudit " + auditId + " not found"));

        audit.setPhysicalCount(counted);
        Integer theoretical = audit.getTheoreticalCount();
        int discrepancy = theoretical == null ? 0 : Math.abs(theoretical - counted);
        audit.setDiscrepancyCount(discrepancy);

        if (theoretical != null && counted != theoretical) {
            audit.setAuditMode(AuditMode.SCAN_ONE_BY_ONE);
        }
        if (audit.getStatus() == AuditStatus.SCHEDULED) {
            audit.setStatus(AuditStatus.IN_PROGRESS);
        }

        audit = stockAuditRepository.save(audit);
        return stockAuditMapper.toDto(audit);
    }

    /**
     * Register an IMEI scan against an audit.
     *
     * <p>If the scanned IMEI corresponds to a {@link StockItem} that belongs to
     * the audited warehouse, a {@link StockAuditLine} with resolution
     * {@link AuditResolution#FOUND} is created (or updated to FOUND if it
     * already existed). Otherwise a line with resolution
     * {@link AuditResolution#UNEXPECTED} is created.</p>
     *
     * @return the newly persisted (or updated) audit line.
     */
    public StockAuditLine scanLine(Long auditId, String imei) {
        log.debug("Request to register scan IMEI {} on audit {}", imei, auditId);
        StockAudit audit = stockAuditRepository
            .findOneWithEagerRelationships(auditId)
            .orElseThrow(() -> new NoSuchElementException("StockAudit " + auditId + " not found"));

        StockItem item = stockItemRepository
            .findOneByImeiWithEagerRelationships(imei)
            .orElseThrow(() -> new NoSuchElementException("Unknown IMEI: " + imei));

        boolean inPerimeter =
            item.getWarehouse() != null && audit.getWarehouse() != null && item.getWarehouse().getId().equals(audit.getWarehouse().getId());

        StockAuditLine line = new StockAuditLine()
            .stockItem(item)
            .audit(audit)
            .foundPhysically(true)
            .createdAt(ZonedDateTime.now())
            .resolution(inPerimeter ? AuditResolution.FOUND : AuditResolution.UNEXPECTED);
        if (!inPerimeter) {
            line.setResolutionNote("Item not in audited warehouse perimeter");
        }
        line = stockAuditLineRepository.save(line);

        if (audit.getStatus() == AuditStatus.SCHEDULED) {
            audit.setStatus(AuditStatus.IN_PROGRESS);
            stockAuditRepository.save(audit);
        }

        return line;
    }

    /**
     * Close an audit, comparing its result against its parallel-paired audit
     * (commercial vs magasinier). When a discrepancy is detected, both audits
     * are forced back to {@link AuditStatus#REOPENED} and an
     * {@code AUDIT_DISCREPANCY} notification is emitted.
     *
     * <p>"Discrepancy" is defined as the two audits disagreeing on either the
     * physical count or the discrepancy count.</p>
     *
     * @return the (possibly REOPENED) primary audit DTO.
     */
    public StockAuditDTO closeWithParallel(Long auditId) {
        log.debug("Request to close audit {} with parallel reconciliation", auditId);
        StockAudit audit = stockAuditRepository
            .findById(auditId)
            .orElseThrow(() -> new NoSuchElementException("StockAudit " + auditId + " not found"));

        // First close the primary audit.
        audit.setStatus(AuditStatus.CLOSED);
        audit.setClosedAt(ZonedDateTime.now());
        audit = stockAuditRepository.save(audit);

        Long parallelId = audit.getParallelOf();
        if (parallelId == null) {
            return stockAuditMapper.toDto(audit);
        }

        Optional<StockAudit> parallelOpt = stockAuditRepository.findById(parallelId);
        if (parallelOpt.isEmpty()) {
            log.warn("Audit {} references missing parallel audit {}", auditId, parallelId);
            return stockAuditMapper.toDto(audit);
        }
        StockAudit parallel = parallelOpt.get();

        if (hasDiscrepancyWith(audit, parallel)) {
            log.info("Discrepancy detected between audit {} and parallel {} - reopening both", audit.getId(), parallel.getId());
            audit.setStatus(AuditStatus.REOPENED);
            parallel.setStatus(AuditStatus.REOPENED);
            audit = stockAuditRepository.save(audit);
            stockAuditRepository.save(parallel);

            try {
                notificationClient.publish(
                    new NotificationPayloadDTO(
                        "*ADMIN_COMMERCIAL*",
                        "AUDIT_DISCREPANCY",
                        "Audit discrepancy detected",
                        "Audits #" + audit.getId() + " and #" + parallel.getId() + " disagree and have been reopened.",
                        "{\"auditId\":" + audit.getId() + ",\"parallelOf\":" + parallel.getId() + "}"
                    )
                );
            } catch (Exception ex) {
                log.warn("Failed to publish AUDIT_DISCREPANCY notification: {}", ex.getMessage());
            }
        }

        return stockAuditMapper.toDto(audit);
    }

    private boolean hasDiscrepancyWith(StockAudit a, StockAudit b) {
        Integer pa = a.getPhysicalCount();
        Integer pb = b.getPhysicalCount();
        Integer da = a.getDiscrepancyCount();
        Integer db = b.getDiscrepancyCount();
        if (pa == null && pb == null && da == null && db == null) {
            return false;
        }
        return !nullSafeEquals(pa, pb) || !nullSafeEquals(da, db);
    }

    private static boolean nullSafeEquals(Integer x, Integer y) {
        if (x == null && y == null) {
            return true;
        }
        if (x == null || y == null) {
            return false;
        }
        return x.intValue() == y.intValue();
    }
}
